# -*- coding: utf-8 -*-
"""BarPlot_SuicideAnalysisIndia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EFFBTB1MkvVR8udNLBLnUmnNNkzceZra
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

suicide_data = pd.read_csv('/content/Suicides in India 2001-2012.csv')

suicide_data.info()

suicide_data.head()

type_sum = suicide_data.groupby('Type')['Total'].sum()
a = type_sum.sort_values(ascending=False).head(10)
a

fig = plt.figure(figsize=(12,6))
sns.barplot(x = a.index, y = a.values)

b = suicide_data.groupby('State')['Total'].sum().sort_values(ascending=False).head(10)
b

fig = plt.figure(figsize=(12,6))
sns.barplot(x = b.index, y = b.values)

c = suicide_data.groupby(['Year'])['Total'].sum()
c

fig = plt.figure(figsize=(12,6))
sns.barplot(x = c.index, y = c.values)

s = suicide_data.groupby(['State','Type'])['Total'].sum()
s

type_suicide = s[s.groupby('State').transform(lambda x: x == x.max())]

type_suicide

type(type_suicide)

fig = plt.figure(figsize=(12,6))
type_suicide.droplevel(level=1).plot(kind = 'bar')

fig = plt.figure(figsize=(12,6))
type_suicide.droplevel(level=0).groupby('Type').sum().plot(kind = 'bar')
