# -*- coding: utf-8 -*-
"""Box_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IaEXSxchV6M3WGo-do2JTRfixYPHnohX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('2015.csv')

df.head()

sns.boxplot('Happiness Score', data = df);

sns.boxplot(x = 'Happiness Score', whis = 0.2, data = df);

sns.boxplot(x = 'Happiness Score', whis = 0.2, fliersize = 1, data = df)

sns.boxplot(y = 'Happiness Score', whis = 0.2, fliersize = 1, orient = 'v', data = df)

sns.boxplot(df.Generosity)

sns.boxplot(x = 'Economy (GDP per Capita)', data = df);

fig, axs = plt.subplots(nrows=3);
sns.boxplot(df[df.Region == 'Western Europe']['Happiness Score'], ax = axs[0]);
sns.boxplot(df[df.Region == 'Sub-Saharan Africa']['Happiness Score'], ax = axs[1]);
sns.boxplot(df[df.Region == 'North America']['Happiness Score'], ax = axs[2]);
plt.tight_layout()
