# -*- coding: utf-8 -*-
"""Box_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IaEXSxchV6M3WGo-do2JTRfixYPHnohX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('2015.csv')

df.head()

sns.boxplot('Happiness Score', data = df);

sns.boxplot(x = 'Happiness Score', whis = 0.2, data = df);

sns.boxplot(x = 'Happiness Score', whis = 0.2, fliersize = 1, data = df)

sns.boxplot(y = 'Happiness Score', whis = 0.2, fliersize = 1, orient = 'v', data = df)

sns.boxplot(df.Generosity)

sns.boxplot(x = 'Economy (GDP per Capita)', data = df);

fig, axs = plt.subplots(nrows=3);
p1 = sns.boxplot(df[df.Region == 'Western Europe']['Happiness Score'], ax = axs[0]);
p1.set_title('Western Europe');
p2 = sns.boxplot(df[df.Region == 'Sub-Saharan Africa']['Happiness Score'], ax = axs[1]);
p2.set_title('Sub-Saharan Africa');
p3 = sns.boxplot(df[df.Region == 'North America']['Happiness Score'], ax = axs[2]);
p3.set_title('North America');
plt.tight_layout()

g = sns.FacetGrid(df, row = 'Region');
g.map(sns.boxplot, 'Happiness Score');

g = sns.FacetGrid(df2, col = 'Region', row = 'Country');
g.map(sns.boxplot, 'Happiness Score');
