# -*- coding: utf-8 -*-
"""HeatMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jP9TJh_WYQ_Lf5IBxjHbw0BuYEi_I7Ea
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Suicides in India 2001-2012.csv')

df.head()

df_a = df.groupby(['State','Year'])['Total'].sum()
df_a

df_b = pd.DataFrame(df_a)

df_b = df_a.unstack(level=1)
df_b.head()

fig = plt.gcf();
fig.set_size_inches(15,10);
sns.heatmap(df_b, annot = True, fmt = 'd', cmap = 'YlGnBu');

x = np.random.rand(10,10)

sns.heatmap(x, annot = True, cmap = 'coolwarm');
plt.tight_layout();