# -*- coding: utf-8 -*-
"""Violin_Plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13vLcfCjmFLPS6ZhgPEVqKYL4EVmeTXFE
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('data.csv')

df.head()

df['AGE_2'] = df['AGE'].apply(lambda x: 0 if x <= 50 else 1)

df.head()

sns.violinplot(x = 'AGE', data = df);

sns.violinplot(y = 'AGE', data = df, orient = 'v');

sns.violinplot(y = 'AGE', data = df, inner = 'quartile', orient = 'v');

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'DIS', data = df);

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'B', data = df);

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'CHAS', data = df);

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'CHAS', hue = 'AGE_2', data = df);

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'CHAS', hue = 'AGE_2', split = True, data = df);

fig = plt.figure(figsize=(8,4))
sns.violinplot(x = 'RAD', y = 'CHAS', hue = 'AGE_2', split = True, inner = 'quartile', data = df);